import { v4 as uuidv4 } from 'uuid';
import member1 from '../../assets/img/products/Accsessories/1.png'; // Antes Full-Face-Shield-Mesh.png
import member2 from '../../assets/img/products/Accsessories/6.png'; // Antes Eye-Shield-Clear-Anti-Fog-removebg-preview.png
import member3 from '../../assets/img/products/Accsessories/3.png'; // Antes Replaceable-Suspension-Kit-removebg-preview.png
import member4 from '../../assets/img/products/Accsessories/4.png'; // Antes Full-Face-Shield-Clear-removebg-preview.png
import member5 from '../../assets/img/products/Accsessories/5.png'; // Antes otro Full-Face-Shield-Mesh.png
import member6 from '../../assets/img/products/Accsessories/2.png'; // Antes Replaceable-Chin-Strap-removebg-preview.png
import member7 from '../../assets/img/products/Accsessories/7.png'; // Antes High-Vis-Reflective-Sticker-removebg-preview.png
import member8 from '../../assets/img/products/Accsessories/8.png'; // Antes Winter-Cap-removebg-preview.png
import member9 from '../../assets/img/products/Accsessories/9.png'; // Antes Replaceable-Pad-Kit-removebg-preview.png
import member10 from '../../assets/img/products/Accsessories/10.png'; // Antes Mounted-Earmuff-removebg-preview.png
import member11 from '../../assets/img/products/Accsessories/11.png'; // Antes Replaceable-Wheel-Rachet-removebg-preview.png
import member12 from '../../assets/img/products/Accsessories/12.png'; // Antes Universal-Head-Lamp-removebg-preview.png
import member13 from '../../assets/img/products/Accsessories/13.png';
import member14 from '../../assets/img/products/Accsessories/14.png';
import member15 from '../../assets/img/products/Accsessories/15.png';
import member16 from '../../assets/img/products/Accsessories/16.png';
const teamData = [
    {
        id: uuidv4(),
        img: member1,
        name: 'Mounted Earmuff',
        position: 'M12',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member1,
        name: 'Mounted Earmuff',
        position: 'M10',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member1,
        name: 'Mounted Earmuff',
        position: 'M02',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },

    {
        id: uuidv4(),
        img: member2,
        name: 'Full Face Shield Mesh',
        position: 'M12',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member2,
        name: 'Full Face Shield Mesh',
        position: 'M02',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member2,
        name: 'Full Face Shield Mesh',
        position: 'M10',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },


    {
        id: uuidv4(),
        img: member4,
        name: 'Replaceable Suspension Kit',
        position: 'M12',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member4,
        name: 'Replaceable Suspension Kit',
        position: 'M10',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member4,
        name: 'Replaceable Suspension Kit',
        position: 'M02',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member6,
        name: 'Replaceable Chin Strap',
        position: 'M12',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member7,
        name: 'Full Face Shield Clear',
        position: 'M12',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member8,
        name: 'Eye Shield Clear Anti-Fog',
        position: 'M12',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member9,
        name: 'Winter Cap',
        position: 'M12',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member10,
        name: 'Eye shield Mirror Anti-Fog',
        position: 'M12',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member11,
        name: 'High Vis Reflective Sticker',
        position: 'M12',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member12,
        name: 'Universal Head Lamp',
        position: 'M12',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },{
        id: uuidv4(),
        img: member6,
        name: 'Replaceable Chin Strap',
        position: 'M10',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member7,
        name: 'Full Face Shield Clear',
        position: 'M10',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member8,
        name: 'Eye Shield Clear Anti-Fog',
        position: 'M10',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member9,
        name: 'Winter Cap',
        position: 'M10',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member10,
        name: 'Eye shield Mirror Anti-Fog',
        position: 'M10',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member11,
        name: 'High Vis Reflective Sticker',
        position: 'M10',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member12,
        name: 'Universal Head Lamp',
        position: 'M10',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member6,
        name: 'Replaceable Chin Strap',
        position: 'M02',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member7,
        name: 'Full Face Shield Clear',
        position: 'M02',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member8,
        name: 'Eye Shield Clear Anti-Fog',
        position: 'M02',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member9,
        name: 'Winter Cap',
        position: 'M02',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member10,
        name: 'Eye shield Mirror Anti-Fog',
        position: 'M02',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member11,
        name: 'High Vis Reflective Sticker',
        position: 'M02',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member12,
        name: 'Universal Head Lamp',
        position: 'M02',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
        
   
 {
        id: uuidv4(),
        img: member3,
        name: 'Replaceable Wheel Rachet',
        position: 'M02',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    }, {
        id: uuidv4(),
        img: member13,
        name: 'Replaceable Wheel Rachet',
        position: 'M10',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
    {
        id: uuidv4(),
        img: member15,
        name: 'Replaceable Wheel Rachet',
        position: 'M12',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
     {
        id: uuidv4(),
        img: member5,
        name: 'Replaceable Pad Kit',
        position: 'M02',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },  {
        id: uuidv4(),
        img: member16,
        name: 'Replaceable Pad Kit',
        position: 'M10',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },  {
        id: uuidv4(),
        img: member14,
        name: 'Replaceable Pad Kit',
        position: 'M12',
        fbLink: '/',
        twitterLink: '/',
        behanceLink: '/',
        youtubeLink: '/',
    },
];

export default teamData;